name: Deploy assets

on:
  push:
    branches:
      - master
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.3
      with:
        node-version: '12.13.1'

    - name: Get version
      id: version
      uses: notiz-dev/github-action-json-property@release
      with: 
          path: 'package.json'
          prop_path: 'version'

    - name: Check folder doesn't exist
      if: github.ref == 'refs/heads/master'
      uses: tuler/s3-check-action@master
      id: check
      env:
        FILE: 'prod/${{steps.version.outputs.prop}}/smbc-frontend.min.css'
        AWS_REGION: 'eu-west-1'
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: S3 check failure
      if: github.ref == 'refs/heads/master' && steps.check.outputs.exists == 'true'
      run: |
        echo "S3 folder already exists for version ${{steps.version.outputs.prop}}"
        exit 1

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test

    - name: Build assets
      run: npm run build:dist
    
    - name: Set environment
      id: set_env
      run: |
        if [$REF == 'refs/heads/master']
        then
          echo "::set-output name=env::prod"
        else
          echo "::set-output name=env::int"
        fi
      env:
        REF: ${{ github.ref }}

    - name: S3 sync
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'eu-west-1'
        SOURCE_DIR: './dist'
        DEST_DIR: '${{steps.set_env.outputs.env}}/${{steps.version.outputs.prop}}'
