name: Test application

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.0
      with:
        node-version: '12.13.1'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test
